language: go

go:
- 1.13

services:
- docker

install: true

env:
- GO111MODULE=on

branches:
  only:
  - master

before_install:
- |
  set -e
  make install-ci
 
script:
- |
  set -e
  make test test-e2e

after_success:
  - bash <(curl -s https://codecov.io/bash) -f '*.out'