apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        # Expected UID for the nonuser:nonuser group in distroless
        # This is needed for ProjectedService accounts to work
        # see https://github.com/kubernetes-sigs/external-dns/pull/1185#issuecomment-530439786 for more information
        fsGroup: 1002
      containers:
      - command:
        - /awsctrl
        args:
        - "start"
        - "--enable-leader-election"
        - "--config-name=awsctrl-config"
        image: controller:latest
        name: manager
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              optional: true
              key: aws-access-key-id
              name:  awsctrl-aws-credentials
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              optional: true
              key: aws-secret-access-key
              name:  awsctrl-aws-credentials
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 256Mi
      terminationGracePeriodSeconds: 10
