
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - apikeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - apikeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - authorizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - authorizers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - basepathmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - basepathmappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - clientcertificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - clientcertificates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - documentationparts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - documentationparts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - documentationversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - documentationversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - domainnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - domainnames/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - gatewayresponses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - gatewayresponses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - methods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - methods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - requestvalidators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - requestvalidators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - resources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - resources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - restapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - restapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - stages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - stages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - usageplankeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - usageplankeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - usageplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - usageplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - vpclinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - vpclinks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - certificatemanager.awsctrl.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certificatemanager.awsctrl.io
  resources:
  - certificates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud9.awsctrl.io
  resources:
  - environmentec2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud9.awsctrl.io
  resources:
  - environmentec2s/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudformation.awsctrl.io
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudformation.awsctrl.io
  resources:
  - stacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ecr.awsctrl.io
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecr.awsctrl.io
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.awsctrl.io
  resources:
  - accesskeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.awsctrl.io
  resources:
  - accesskeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.awsctrl.io
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.awsctrl.io
  resources:
  - groups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.awsctrl.io
  resources:
  - instanceprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.awsctrl.io
  resources:
  - instanceprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.awsctrl.io
  resources:
  - managedpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.awsctrl.io
  resources:
  - managedpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.awsctrl.io
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.awsctrl.io
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.awsctrl.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.awsctrl.io
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.awsctrl.io
  resources:
  - servicelinkedroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.awsctrl.io
  resources:
  - servicelinkedroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.awsctrl.io
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.awsctrl.io
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.awsctrl.io
  resources:
  - usertogroupadditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.awsctrl.io
  resources:
  - usertogroupadditions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - aliases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - aliases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - eventinvokeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - eventinvokeconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - eventsourcemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - eventsourcemappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - functions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - functions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - layerversionpermissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - layerversionpermissions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - layerversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - layerversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - permissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - permissions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - versions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.awsctrl.io
  resources:
  - versions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route53.awsctrl.io
  resources:
  - healthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route53.awsctrl.io
  resources:
  - healthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route53.awsctrl.io
  resources:
  - hostedzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route53.awsctrl.io
  resources:
  - hostedzones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route53.awsctrl.io
  resources:
  - recordsetgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route53.awsctrl.io
  resources:
  - recordsetgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route53.awsctrl.io
  resources:
  - recordsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route53.awsctrl.io
  resources:
  - recordsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - self.awsctrl.io
  resources:
  - config
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self.awsctrl.io
  resources:
  - config/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - self.awsctrl.io
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self.awsctrl.io
  resources:
  - configs/status
  verbs:
  - get
  - patch
  - update
