
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.awsctrl.io
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud9.awsctrl.io
  resources:
  - environmentec2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud9.awsctrl.io
  resources:
  - environmentec2s/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudformation.awsctrl.io
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudformation.awsctrl.io
  resources:
  - stacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - self.awsctrl.io
  resources:
  - config
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self.awsctrl.io
  resources:
  - config/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - self.awsctrl.io
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self.awsctrl.io
  resources:
  - configs/status
  verbs:
  - get
  - patch
  - update
