apiVersion: cloudformation.awsctrl.io/v1alpha1
kind: Stack
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: stack-sample
spec:
  region: us-west-2
  # capabilities: []
  # notificationARNs: []
  parameters:
    Namespace: "default"
    Name: "awsctrl"
  templateBody: |
    AWSTemplateFormatVersion: 2010-09-09
    Description: 'awsctrl - Amazon ECR Repository'
    Parameters:
      Namespace:
        Type: String
      Name:
        Type: String
    Resources:
      ECRRepository:
        Type: AWS::ECR::Repository
        Properties:
          RepositoryName: !Ref Name
    Outputs:
      Name:
        Value: !Ref ECRRepository
      ARN:
        Value: !GetAtt ECRRepository.Arn