apiVersion: iam.awsctrl.io/v1alpha1
kind: User
metadata:
  name: user-sample
spec:
  capabilities:
  - CAPABILITY_NAMED_IAM
  userName: christopherhein
  # todo(christopherhein) change the code generation to support plural ids and arns
  managedPolicyRefs:
  - arn: arn:aws:iam::aws:policy/AdministratorAccess