apiVersion: lambda.awsctrl.io/v1alpha1
kind: Permission
metadata:
  name: permission-sample
spec: 
  functionName: function-sample
  action: "lambda:InvokeFunction"
  principal: s3.amazonaws.com
  sourceRef: 
    arn: arn:aws:s3:::awsctrl-lambda-s3-trigger