apiVersion: apigateway.awsctrl.io/v1alpha1
kind: Stage
metadata:
  name: stage-sample
spec:
  restApiRef:
    kind: RestApi
    apiVersion: apigateway.awsctrl.io/v1alpha1
    name: restapi-sample
    key: ResourceRef
  stageName: Prod
  description: Prod Stage
  deploymentRef:
    kind: Deployment
    apiVersion: apigateway.awsctrl.io/v1alpha1
    name: deployment-sample
    key: ResourceRef
  documentationVersion: ""
  clientCertificateRef: 
    kind: ClientCertificate
    apiVersion: apigateway.awsctrl.io/v1alpha1
    name: clientcertificate-sample
    key: ResourceRef
  variables:
    stack: Prod
  methodSettings:
  - resourcePath: /
    httpMethod: GET
    metricsEnabled: true
    dataTraceEnabled: true