apiVersion: apigateway.awsctrl.io/v1alpha1
kind: Method
metadata:
  name: method-sample
spec:
  authorizationType: NONE
  httpMethod: POST
  integration:
    integrationHttpMethod: POST
    type: MOCK
  resourceRef: 
    kind: RestApi
    apiVersion: apigateway.awsctrl.io/v1alpha1
    name: restapi-sample
    key: RootResourceId
  restApiRef:
    kind: RestApi
    apiVersion: apigateway.awsctrl.io/v1alpha1
    name: restapi-sample
    key: ResourceRef