apiVersion: apigateway.awsctrl.io/v1alpha1
kind: Resource
metadata:
  name: resource-sample
spec:
  pathPart: stack
  restApiRef:
    kind: RestApi
    apiVersion: apigateway.awsctrl.io/v1alpha1
    name: restapi-sample
    key: ResourceRef
  parentRef:
    kind: RestApi
    apiVersion: apigateway.awsctrl.io/v1alpha1
    name: restapi-sample
    key: RootResourceId