apiVersion: apigateway.awsctrl.io/v1alpha1
kind: ApiKey
metadata:
  name: apikey-sample
spec: 
  name: "sample-apikey"
	description: |
    CloudFormation API Key V1"
  enabled: true
  stageKeys:
  - stageName: "Test"
    restApiRef:
      kind: RestApi
      apiVersion: apigateway.awsctrl.io/v1alpha1
      name: restapi-sample
      key: ResourceRef
