apiVersion: route53.awsctrl.io/v1alpha1
kind: HostedZone
metadata:
  name: hostedzone-sample
spec:
  terminationProtection: true
  name: "e2e.awsctrl.io"
  hostedZoneConfig: 
    comment: |
      Controller created hosted zone